<a href="https://colab.research.google.com/github/rishav-raj-genx/Data_Science_26/blob/main/Numpy_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Function.     | Primary Use       | CaseOutput

array() | Convert a list to an array | [1, 2, 3]

zeros()| Array filled with 0s | [0., 0., 0.]

ones() | Array filled with 1s | [1., 1., 1.]

empty() | Uninitialized memory (fastest) | [4.9e-324, 9.8e-324]

full() | Array filled with a custom value | [7, 7, 7]

arange() | Sequence based on a step size | [0, 2, 4, 6]

linspace() | Sequence based on total number of items | [0., 0.5, 1.]

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.array(['2',8,9,27,61])
print(b) #Only allows one datatype - thus converting the other datatype value in the same datatype

[1 2 3 4 5 6 7 8]
['2' '8' '9' '27' '61']


In [ ]:
np_arr = np.array([2,3,4,5,6,21, 'hello', False]) #converts all the value into string
print(np_arr)
print(bool(np_arr[-1])) #string is always true except empty string
a = False
print(bool(a))

['2' '3' '4' '5' '6' '21' 'hello' 'False']
True
False


In [ ]:
a = np.zeros([2,3,4])
print(a)
b = np.zeros([2,5,6])
print(b)
c = np.zeros(5)
print(c)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
[0. 0. 0. 0. 0.]


In [ ]:
a = np.empty([2,3,3], dtype=int)
print(a)
print(type(a[0][0][0]))

[[[         983276985                  0    281479277510657]
  [105553498576781433    138066018698496                145]
  [         979570272    138067573124448        51539608082]]

 [[      176093659666          976328688        60129542145]
  [                 0                 81    138067573124320]
  [   138067573124320          976326896          976327504]]]
<class 'numpy.int64'>


In [ ]:
a = np.full(4,8,dtype = int)
print(a)

[8 8 8 8]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#To check dimension of the array - a.ndmim

0
1
2
3


In [ ]:
sevens = np.full((2, 4), 7)
print(sevens)

In [ ]:
seq = np.arange(10)
evens = np.arange(2, 11, 2)
print(seq)
print(evens)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]


In [ ]:
linear = np.linspace(0, 1, 23, dtype = float)
print(linear)

[0.         0.04545455 0.09090909 0.13636364 0.18181818 0.22727273
 0.27272727 0.31818182 0.36363636 0.40909091 0.45454545 0.5
 0.54545455 0.59090909 0.63636364 0.68181818 0.72727273 0.77272727
 0.81818182 0.86363636 0.90909091 0.95454545 1.        ]


In [ ]:
One = np.array([[2,3,4],[4,5,7]])
print(One)
Two = One.shape
print(Two)
Three = One.size
print(Three)

[[2 3 4]
 [4 5 7]]
(2, 3)
6


In [ ]:
my_array = np.array([[10, 20, 30],
                     [40, 50, 60]])
print(my_array.dtype)
float_array = np.array([1, 2, 3], dtype='float32')
print(float_array.dtype)

int64
float32


In [ ]:
no1 = np.random.randint(17)
print(no1)
arr_1d = np.random.randint(10, 50, size=5)
print(arr_1d)
matrix = np.random.randint(1, 6, size=(3, 3))
print(matrix)

10
[17 48 36 26 27]
[[2 4 5]
 [2 2 3]
 [5 5 4]]


In [ ]:
n = np.random.randint(1, 46, size=8)
print(n)

[ 6  5 31 14 33  3 13 10]


In [ ]:
options = ['Apple', 'Banana', 'Cherry', 'Date']
pick_one = np.random.choice(options)
print(pick_one)
pick_three = np.random.choice(options, size=3)
print(pick_three)
no_dupes = np.random.choice(options, size=3, replace=False)
print(no_dupes)
no = np.random.choice(5, 3, replace=False)
print(no)
noi = np.random.choice([23,43,13,42], 3)
print(noi)

Date
['Apple' 'Banana' 'Cherry']
['Date' 'Cherry' 'Apple']
[2 0 3]
[43 13 23]


In [ ]:
n = np.array([[[22,33,44],[99,88,77],[55,11,66]]])
print(n)
n1 = np.array([[[110,121,132],[143,154,165],[176,187,198]]])
print(n1)
print(n*2)
print(n+n1)
print(n*n1)
print(n/n1)
print(n+2)
print(n-n1)

[[[22 33 44]
  [99 88 77]
  [55 11 66]]]
[[[110 121 132]
  [143 154 165]
  [176 187 198]]]
[[[ 44  66  88]
  [198 176 154]
  [110  22 132]]]
[[[132 154 176]
  [242 242 242]
  [231 198 264]]]
[[[ 2420  3993  5808]
  [14157 13552 12705]
  [ 9680  2057 13068]]]
[[[0.2        0.27272727 0.33333333]
  [0.69230769 0.57142857 0.46666667]
  [0.3125     0.05882353 0.33333333]]]
[[[ 24  35  46]
  [101  90  79]
  [ 57  13  68]]]
[[[ -88  -88  -88]
  [ -44  -66  -88]
  [-121 -176 -132]]]


In [ ]:
m = np.array([[[1,2,3],[4,5,6]]])
print(m)
n = np.array([[1,3,3],[8,9,2]])
print(n)
print(m*n)

[[[1 2 3]
  [4 5 6]]]
[[1 3 3]
 [8 9 2]]
[[[ 1  6  9]
  [32 45 12]]]


In [ ]:
matrix = np.array([[1, 1, 1],
                   [2, 2, 2],
                   [3, 3, 3]])
row = np.array([10, 20, 30])
result = matrix + row
print("Result:\n", result)

Result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
matrix = np.ones((3, 3))
wrong_row = np.array([1, 2])

try:
    result = matrix + wrong_row
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (3,3) (2,) 


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
grid = arr.reshape(2, 3)
print(grid)
auto_grid = arr.reshape(-1, 2)
print(auto_grid)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
flipped = matrix.T
print(flipped)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6]])
vert = np.concatenate((A, B), axis=0)
print(vert)
horiz = np.concatenate((A, B.T), axis=1)
print(horiz)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.where(arr > 25)
new_arr = np.where(arr > 25, 100, arr)
print(new_arr)

In [ ]:
arr = np.array([5, 1, 9, 3])
sorted_arr = np.sort(arr)
print(sorted_arr)
matrix = np.array([[8, 4],
                   [2, 9]])
print(np.sort(matrix))

In [ ]:
scores = np.array([[10, 20],
                   [30, 40]])

print(np.sum(scores))
print(np.sum(scores, axis=0))
print(np.sum(scores, axis=1))

In [ ]:
print(np.min(scores))
print(np.min(scores, axis=0))

In [ ]:
data = np.array([2, 4, 4, 4, 5, 5, 7, 9])
print(np.mean(data))
print(np.std(data))

5.0
2.0


In [ ]:
a = np.random.randint(2, 19, 7)
b = np.random.randint(1, 17, 4)
print("--- 1D Concatenations ---")
print(np.concatenate((a, b)))
print(np.concatenate((b, a)))
print("\n--- Correct 2D Concatenation along axis=1 ---")
a_2d = np.random.randint(2, 19, size=(3, 7)) # 3 rows, 7 columns
b_2d = np.random.randint(1, 17, size=(3, 4)) # 3 rows, 4 columns
print(np.concatenate((a_2d, b_2d), axis=1))

In [ ]:
a = np.random.randint(2, 19, 7)
b = np.random.randint(1, 17, 7)
c = np.where(b > 2, b,a)
print(a)
print(b)
print(c)

[12 16  3 16  2 17  8]
[ 9 11 15  4  8  8  8]
[ 9 11 15  4  8  8  8]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 1],
              [2, 3]])
result = np.matmul(A, B)
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Shape of Result:", result.shape)
print("Result:\n", result)

Shape of A: (2, 3)
Shape of B: (3, 2)
Shape of Result: (2, 2)
Result:
 [[31 19]
 [85 55]]


In [ ]:
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])
result = vector_1 @ vector_2
print(result)

In [ ]:
Cricket = np.random.randint(0, 151, size=7)
print(Cricket)
total_score = np.sum(Cricket)
print(total_score)
max_score = np.max(Cricket)
print(max_score)
min_score = np.min(Cricket)
print(min_score)
average_score = np.mean(Cricket)
print(average_score)
standard_deviation = np.std(Cricket)
print(standard_deviation)

[120  40 119  72   4  59  93]
507
120
4
72.42857142857143
39.22410753917669


In [ ]:
import numpy as np
n = input("Enter cricket scores separated by spaces (e.g., 45 102 12 88): ")
cri = [int(num) for num in n.split()]
cric = np.array(cri)
print("\n--- Tournament Scorecard ---")
print(" Day   |  Score ")
print("----------------")
for index, score in enumerate(cric):
    print(f" Day {index + 1} |   {score}")
print("----------------")
print("\n--- Player Statistics ---")
print(f"Original Array:     {cric}")
print(f"Highest Score:      {np.max(cric)}")
print(f"Lowest Score:       {np.min(cric)}")
print(f"Average (Mean):     {np.mean(cric):.2f}")
print(f"Standard Deviation: {np.std(cric):.2f}")
print(f"Unique Scores:      {np.unique(cric)}")
print(f"Sorted Scores:      {np.sort(cric)}")

Enter cricket scores separated by spaces (e.g., 45 102 12 88): 54 26 76 62 100 17 98

--- Tournament Scorecard ---
 Day   |  Score 
----------------
 Day 1 |   54
 Day 2 |   26
 Day 3 |   76
 Day 4 |   62
 Day 5 |   100
 Day 6 |   17
 Day 7 |   98
----------------

--- Player Statistics ---
Original Array:     [ 54  26  76  62 100  17  98]
Highest Score:      100
Lowest Score:       17
Average (Mean):     61.86
Standard Deviation: 30.05
Unique Scores:      [ 17  26  54  62  76  98 100]
Sorted Scores:      [ 17  26  54  62  76  98 100]


In [ ]:
scores - []
days = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun']
for day in days:
    score = int(input(f"Enter the score for {day}: "))
    scores.append(score)
#scores = [] days = ['Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun'] for day in range(7): score = input(f"Enter the score for {days[day]}: ") scores.append(score)


In [ ]:
scores = input().split()
print(scores)
final_scores = [int(score) for score in scores]
print(final_scores)
#input().split()

In [ ]:
a = np.array([3,3,3,3])
b = a
b[0] = 1
print(a,b)

[1 3 3 3] [1 3 3 3]


A shop - we need a price input from the user and find the max price, stand deviation, mini price, total price, mean

In [ ]:
import numpy as np
items = []
prices_of_the_respective_item = []
for i in range(7):
    name = input(f"Enter name of item {i+1}: ")
    price = float(input(f"Enter price of {name}: "))
    items.append(name)
    prices_of_the_respective_item.append(price)
prices = np.array(prices_of_the_respective_item)
print(prices)
max_price_product = np.max(prices)
min_price_product = np.min(prices)
mean_price_of_products = np.mean(prices)
std_price_of_products = np.std(prices)
max_item = items[np.argmax(prices)]
min_item = items[np.argmin(prices)]
print("\n----- Results -----")
print(f"Most expensive item : {max_item} (₹{max_price_product})")
print(f"Cheapest item       : {min_item} (₹{min_price_product})")
print(f"Average price       : ₹{mean_price_of_products:.2f}")
print(f"Standard Deviation  : ₹{std_price_of_products:.2f}")

Enter name of item 1: a
Enter price of a: 67
Enter name of item 2: s
Enter price of s: 87
Enter name of item 3: d
Enter price of d: 789
Enter name of item 4: f
Enter price of f: 987
Enter name of item 5: f
Enter price of f: 0987
Enter name of item 6: ds
Enter price of ds: 87678
Enter name of item 7: fs
Enter price of fs: 7678
[6.7000e+01 8.7000e+01 7.8900e+02 9.8700e+02 9.8700e+02 8.7678e+04
 7.6780e+03]

----- Results -----
Most expensive item : ds (₹87678.0)
Cheapest item       : a (₹67.0)
Average price       : ₹14039.00
Standard Deviation  : ₹30164.58
