<a href="https://colab.research.google.com/github/rishav-raj-genx/Data_Science_26/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Question 1:
import numpy as np

# Create a 5×5 matrix of random integers (1–90).
mat = np.random.randint(1, 91, size=(5, 5))
print("matrix : ", mat)

# Find mean of values row and column wise
row_wise_mean = np.mean(mat, axis = 1)
column_wise_mean = np.mean(mat, axis = 0)

print("rowwise mean : ", row_wise_mean)
print("column mean : ", column_wise_mean)

# Replace all even numbers with -1
modified_mat = np.where(mat % 2 == 0, -1, mat)
print("modified : ", modified_mat)

# Sort the array row and column wise
sorted_row = np.sort(mat, axis = 1)
sorted_col = np.sort(mat, axis = 0)

print("sorted row : ", sorted_row)
print("sorted col : ", sorted_col)

# Find row and column wise sum saparately
sum_row = np.sum(mat, axis = 1)
sum_col = np.sum(mat, axis = 0)

print("sum row : ", sum_row)
print("sum col : ", sum_col)

# count the number of -ve's in each column
count_col = np.sum(np.where(modified_mat < 0, 1, 0), axis = 0)
print(count_col)

matrix :  [[21 82  9 52 51]
 [47 26 69 38 43]
 [46 13  6 14 16]
 [20 46 27 51 33]
 [88 28 52 62 83]]
rowwise mean :  [43.  44.6 19.  35.4 62.6]
column mean :  [44.4 39.  32.6 43.4 45.2]
modified :  [[21 -1  9 -1 51]
 [47 -1 69 -1 43]
 [-1 13 -1 -1 -1]
 [-1 -1 27 51 33]
 [-1 -1 -1 -1 83]]
sorted row :  [[ 9 21 51 52 82]
 [26 38 43 47 69]
 [ 6 13 14 16 46]
 [20 27 33 46 51]
 [28 52 62 83 88]]
sorted col :  [[20 13  6 14 16]
 [21 26  9 38 33]
 [46 28 27 51 43]
 [47 46 52 52 51]
 [88 82 69 62 83]]
sum row :  [215 223  95 177 313]
sum col :  [222 195 163 217 226]
[3 4 2 4 1]


In [2]:
# Question 2:

# Inventory Control System

# Task:

# Create a 5×5 array (stock levels)
stock = np.random.randint(20, 80, (5, 5))

# Create another 5×5 array (demand)
demand = np.random.randint(20, 80, (5, 5))

print(stock)
print(demand)

# Compute:
# Remaining stock = stock - demand
remaining_stock = stock - demand
print(remaining_stock)

# Replace:
# Negative values → 0 (out of stock)
modified = np.where(remaining_stock < 0, 0, remaining_stock)

# Find:
# Total shortage
total_shortage = np.sum(np.where(remaining_stock < 0, remaining_stock * -1, 0), axis = 0)

# Products with zero stock
product_shortage = np.sum(np.where(remaining_stock < 0, 1, 0), axis = 0)
print(product_shortage)

# Sort each row based on remaining stock
sorted = np.sort(modified, axis = 1)


[[41 23 52 21 23]
 [44 20 44 22 45]
 [62 23 50 22 57]
 [45 57 66 54 48]
 [48 72 56 22 39]]
[[70 57 62 77 66]
 [20 23 45 36 30]
 [62 61 66 20 62]
 [44 23 79 49 71]
 [52 56 26 41 20]]
[[-29 -34 -10 -56 -43]
 [ 24  -3  -1 -14  15]
 [  0 -38 -16   2  -5]
 [  1  34 -13   5 -23]
 [ -4  16  30 -19  19]]
[2 3 4 3 3]


In [5]:
import pandas as pd

file_ = pd.read_csv('/student_data.csv', sep=',')

print(file_.tail(8))

      study_hours  attendance  sleep_hours  internet_usage  \
9992            5         100            9               2   
9993           10          86            9               9   
9994            4          53            7               8   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
9992                      9              62      100.00           Placed  
9993                     15              63      100.00           Placed  
9994                     10              71       85.02           Placed  
9995                      8              88       69.31       Not Placed  
9996                      4              87      100.00           

In [6]:
# Import pandas library
import pandas as pd

# Create a Series
pd.Series()

# Create a DataFrame
pd.DataFrame()

# Read data from a CSV file
pd.read_csv()

# Read data from an Excel file
pd.read_excel()

# Read data from a JSON file
pd.read_json()

# Display the first 5 rows
df.head()

# Display the last 5 rows
df.tail()

# Show DataFrame information (columns, types, null values)
df.info()

# Generate statistical summary
df.describe()

# Return DataFrame dimensions (rows, columns)
df.shape

# Display column names
df.columns

# Display row index labels
df.index

# Select a column
df["column_name"]

# Select rows/columns by label
df.loc[]

# Select rows/columns by integer position
df.iloc[]

# Filter rows based on a condition
df[df["Age"] > 25]

# Add or update a column
df["new_column"] = values

# Rename columns
df.rename()

# Remove rows or columns
df.drop()

# Sort values by column
df.sort_values()

# Check for missing values
df.isnull()

# Check for non-missing values
df.notnull()

# Count missing values
df.isnull().sum()

# Replace missing values
df.fillna()

# Remove missing values
df.dropna()

# Replace specific values
df.replace()

# Find unique values
df.unique()

# Count unique values
df.nunique()

# Group data and aggregate
df.groupby()

# Aggregate multiple statistics
df.agg()

# Apply a function to values
df.apply()

# Apply function element-wise
df.map()

# Merge DataFrames (SQL-style join)
pd.merge()

# Concatenate DataFrames
pd.concat()

# Join DataFrames using index
df.join()

# Create a pivot table
df.pivot_table()

# Reshape data from wide to long
pd.melt()

# Convert column to datetime
pd.to_datetime()

# Extract year from datetime
df["date"].dt.year

# Extract month from datetime
df["date"].dt.month

# Extract day from datetime
df["date"].dt.day

# Calculate sum
df.sum()

# Calculate mean
df.mean()

# Calculate median
df.median()

# Find minimum value
df.min()

# Find maximum value
df.max()

# Count non-null values
df.count()

# Calculate standard deviation
df.std()

# Calculate variance
df.var()

# Calculate correlation
df.corr()

# Get cumulative sum
df.cumsum()

# Get cumulative maximum
df.cummax()

# Get cumulative minimum
df.cummin()

# Remove duplicate rows
df.drop_duplicates()

# Check duplicated rows
df.duplicated()

# Sample random rows
df.sample()

# Transpose rows and columns
df.T

# Convert DataFrame to NumPy array
df.to_numpy()

# Convert DataFrame to dictionary
df.to_dict()

# Save DataFrame to CSV
df.to_csv()

# Save DataFrame to Excel
df.to_excel()

# Save DataFrame to JSON
df.to_json()

SyntaxError: invalid syntax (3865523290.py, line 44)